/*
* Ver3.0
* Không đặt ràng buộc vì sẽ bắt lỗi trong APP
*/

CREATE DATABASE QLSieuThiBHX
GO

USE QLSieuThiBHX
GO

--DATETIME
SET DATEFORMAT DMY

--**TABLE
CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) PRIMARY KEY,
    TenNV VARCHAR(50),
    GioiTinh VARCHAR(3),
    NgaySinh DATE,
    DiaChi VARCHAR(50),
    DienThoai VARCHAR(10)
);

CREATE TABLE KHACHHANG (
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH VARCHAR(50),
    DiaChi VARCHAR(50),
    DienThoai VARCHAR(10)
);

CREATE TABLE HOADON (
    MaHD VARCHAR(10) PRIMARY KEY,
    MaKH VARCHAR(10) REFERENCES KHACHHANG(MaKH),
    MaNV VARCHAR(10) REFERENCES NHANVIEN(MaNV),
    NgayLapHD DATE
);

CREATE TABLE SANPHAM (
    MaSP VARCHAR(10) PRIMARY KEY,
    TenSP VARCHAR(50),
    DonViTinh VARCHAR(10),
    DonGia INT
);

CREATE TABLE CHITIETHD (
    MaHD VARCHAR(10),
    MaSP VARCHAR(10),
    SoLuong INT,
    PRIMARY KEY (MaHD, MaSP),
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE KHO (
    MaSP VARCHAR(10) PRIMARY KEY,
    TonKho INT,
    FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

---------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------

--**NHÂN VIÊN
CREATE PROC SP_READ_NHANVIEN
AS
SELECT * FROM NHANVIEN
GO

CREATE PROC SP_ADD_NHANVIEN @MaNV VARCHAR(10), @TenNV VARCHAR(50), @GioiTinh VARCHAR(3), @NgaySinh DATE, @DiaChi VARCHAR(50), @DienThoai VARCHAR(10)
AS
INSERT INTO NHANVIEN(MaNV, TenNV, GioiTinh, NgaySinh, DiaChi, DienThoai)
VALUES (@MaNV,@TenNV,@GioiTinh,@NgaySinh,@DiaChi,@DienThoai)
GO

CREATE PROC SP_UPDATE_NHANVIEN @MaNV VARCHAR(10), @TenNV VARCHAR(50), @GioiTinh VARCHAR(3), @NgaySinh DATE, @DiaChi VARCHAR(50), @DienThoai VARCHAR(10)
AS
BEGIN
UPDATE NHANVIEN
SET TenNV=@TenNV, GioiTinh=@GioiTinh, NgaySinh=@NgaySinh, DiaChi=@DiaChi, DienThoai=@DienThoai
WHERE MaNV=@MaNV
END
GO

CREATE PROC SP_DELETE_NHANVIEN @MaNV VARCHAR(10)
AS
BEGIN
UPDATE HOADON
SET MaNV = 'NV0'
WHERE MaNV = @MaNV;
DELETE FROM NHANVIEN WHERE MaNV=@MaNV;
END
GO

--**KHÁCH HÀNG
CREATE PROC SP_READ_KHACHHANG
AS
SELECT * FROM KHACHHANG
GO

CREATE PROC SP_ADD_KHACHHANG @MaKH VARCHAR(10), @TenKH VARCHAR(50), @DiaChi VARCHAR(50), @DienThoai VARCHAR(10)
AS
INSERT INTO KHACHHANG(MaKH, TenKH, DiaChi, DienThoai)
VALUES (@MaKH, @TenKH, @DiaChi, @DienThoai)
GO

CREATE PROC SP_UPDATE_KHACHHANG @MaKH VARCHAR(10), @TenKH VARCHAR(50), @DiaChi VARCHAR(50), @DienThoai VARCHAR(10)
AS
BEGIN
UPDATE KHACHHANG
SET TenKH=@TenKH, DiaChi=@DiaChi, DienThoai=@DienThoai
WHERE MaKH=@MaKH
END
GO

CREATE PROC SP_DELETE_KHACHHANG @MaKH VARCHAR(10)
AS
BEGIN
UPDATE HOADON
SET MaKH = 'KH0'
WHERE MaKH = @MaKH;
DELETE FROM KHACHHANG WHERE MaKH=@MaKH
END
GO

CREATE PROC SP_SEARCH_KHACHHANG @DienThoai VARCHAR(10)
AS
BEGIN
	SELECT * FROM KHACHHANG
	WHERE KHACHHANG.DienThoai LIKE '%'+@DienThoai+'%'
END
GO

--**SẢN PHẨM
CREATE PROC SP_READ_SANPHAM
AS
SELECT S.MaSP, S.TenSP, K.TonKho, S.DonViTinh, S.DonGia FROM SANPHAM S, KHO K
WHERE S.MaSP=K.MaSP
GO

CREATE PROC SP_READ_SANPHAM_TONGTIEN
AS
SELECT SUM(DonGia) FROM SANPHAM
GO

CREATE PROC SP_ADD_SANPHAM @MaSP VARCHAR(10), @TenSP VARCHAR(50), @TonKho INT, @DonViTinh VARCHAR(10), @DonGia INT
AS
INSERT INTO SANPHAM(MaSP, TenSP, DonViTinh, DonGia)
VALUES (@MaSP, @TenSP, @DonViTinh, @DonGia)

INSERT INTO KHO(MaSP, TonKho)
VALUES (@MaSP, @TonKho)
GO

CREATE PROC SP_UPDATE_SANPHAM @MaSP VARCHAR(10), @TenSP VARCHAR(50), @TonKho INT, @DonViTinh VARCHAR(10), @DonGia INT
AS
BEGIN
UPDATE SANPHAM
SET TenSP=@TenSP, DonViTinh=@DonViTinh, DonGia=@DonGia
WHERE MaSP=@MaSP

UPDATE KHO
SET TonKho=@TonKho
WHERE MaSP=@MaSP
END
GO

CREATE PROC SP_DELETE_SANPHAM @MaSP VARCHAR(10)
AS
BEGIN
UPDATE CHITIETHD
SET MaSP = 'SP0'
WHERE MaSP = @MaSP;

DELETE FROM KHO WHERE MaSP=@MaSP
DELETE FROM SANPHAM WHERE MaSP=@MaSP
END
GO

--**KHO
CREATE PROC SP_READ_KHO
AS
BEGIN
    SELECT K.MaSP, S.TenSP, K.TonKho, S.DonViTinh FROM KHO K, SANPHAM S
	WHERE K.MaSP=S.MaSP
END
GO

CREATE PROC SP_ADD_KHO
    @MaSP VARCHAR(10),
    @TonKho INT
AS
BEGIN
    INSERT INTO KHO (MaSP, TonKho) VALUES (@MaSP, @TonKho);
END
GO

CREATE PROC SP_DELETE_KHO
    @MaSP VARCHAR(10)
AS
BEGIN
    DELETE FROM KHO WHERE MaSP = @MaSP;
END
GO

CREATE PROC SP_EDIT_KHO
    @MaSP VARCHAR(10),
    @TonKho INT
AS
BEGIN
    UPDATE KHO SET TonKho = @TonKho WHERE MaSP = @MaSP;
END
GO

CREATE PROC SP_KHO_TongGiaTriSP
AS
SELECT 
    SANPHAM.MaSP,
    TenSP,
    DonViTinh,
    TonKho,
	DonGia,
    DonGia * TonKho AS TổngGiáTrị
FROM 
    SANPHAM
JOIN 
    KHO ON SANPHAM.MaSP = KHO.MaSP;
GO

CREATE PROC SP_KHO_TongKho
AS
SELECT 
    SUM(DonGia * TonKho) AS TổngGiáTrịTấtCảSảnPhẩm
FROM 
    SANPHAM
JOIN 
    KHO ON SANPHAM.MaSP = KHO.MaSP;
GO

--**HOÁ ĐƠN
CREATE PROC SP_READ_HOADON
AS
SELECT * FROM HOADON
GO

CREATE PROC SP_ADD_HOADON @MaHD VARCHAR(10), @MaKH VARCHAR(10), @MaNV VARCHAR(10), @NgayLapHD DATE
AS
INSERT INTO HOADON(MaHD, MaKH, MaNV, NgayLapHD)
VALUES (@MaHD, @MaKH, @MaNV, @NgayLapHD)
GO

CREATE PROC SP_UPDATE_HOADON @MaHD VARCHAR(10), @MaKH VARCHAR(10), @MaNV VARCHAR(10), @NgayLapHD DATE
AS
BEGIN
UPDATE HOADON
SET MaKH = @MaKH, MaNV=@MaNV, NgayLapHD=@NgayLapHD
WHERE MaHD=@MaHD
END
GO

CREATE PROC SP_DELETE_HOADON @MaHD VARCHAR(10)
AS
BEGIN
DELETE CHITIETHD WHERE MaHD=@MaHD	

DELETE FROM HOADON WHERE MaHD=@MaHD
END
GO

CREATE PROC SP_HoaDon_YearMin_Max
AS
SELECT 
    MIN(YEAR(NgayLapHD)) AS NamMin,
    MAX(YEAR(NgayLapHD)) AS NamMax
FROM 
    HOADON;
GO

--**CHI TIẾT HOÁ ĐƠN
CREATE PROC SP_READ_CHITIETHD
AS
BEGIN
SELECT CT.MaHD, NgayLapHD, SUM(CT.SoLuong * SP.DonGia) AS "TongGiaTien"
FROM CHITIETHD CT, HOADON HD, SANPHAM SP
WHERE CT.MaHD=HD.MaHD AND CT.MaSP=SP.MaSP
GROUP BY CT.MaHD, NgayLapHD
END
GO

CREATE PROC SP_ADD_CHITIETHD @MaHD VARCHAR(10), @MaSP VARCHAR(10), @SoLuong INT
AS
INSERT INTO CHITIETHD(MaHD, MaSP, SoLuong)
VALUES (@MaHD, @MaSP, @SoLuong)
GO

CREATE PROC SP_UPDATE_CHITIETHD_THEMMOI @MaHD VARCHAR(10), @MaSP VARCHAR(10),  @SoLuong INT
AS
BEGIN
UPDATE CHITIETHD
SET SoLuong=@SoLuong
WHERE MaHD=@MaHD AND MaSP=@MaSP;	
END
GO
CREATE PROC SP_UPDATE_CHITIETHD_THEMVAO @MaHD VARCHAR(10), @MaSP VARCHAR(10),  @SoLuong INT
AS
BEGIN
UPDATE CHITIETHD
SET SoLuong+=@SoLuong
WHERE MaHD=@MaHD AND MaSP=@MaSP;
END
GO

CREATE PROC SP_DELETE_CHITIETHD @MaHD VARCHAR(10), @MaSP VARCHAR(10)
AS
BEGIN
DELETE FROM CHITIETHD WHERE MaHD=@MaHD AND MaSP=@MaSP
END
GO
--Xuất danh sách SP có trong hoá đơn
CREATE PROC SP_SELECT_CTHD_SANPHAM_of_HD @MaHD VARCHAR(10)
AS
BEGIN
SELECT 
    CHITIETHD.MaHD,
    CHITIETHD.MaSP,
    SANPHAM.TenSP,
    SUM(CHITIETHD.SoLuong) AS TongSoLuong,
    SUM(SANPHAM.DonGia * CHITIETHD.SoLuong) AS ThanhTien
FROM 
    CHITIETHD
JOIN 
    SANPHAM ON CHITIETHD.MaSP = SANPHAM.MaSP
WHERE 
    CHITIETHD.MaHD = @MaHD
GROUP BY 
    CHITIETHD.MaHD, CHITIETHD.MaSP, SANPHAM.TenSP;
END
GO

--**CRYSTAL REPORT
--Đọc danh sách sản phẩm: tênSP(SL).
CREATE PROC SP_READ_SELECT_DSSP_SL @MaHD VARCHAR(10)
AS
BEGIN
SELECT
    STUFF((
        SELECT ', ' + SANPHAM.TenSP + ' (' + CAST(CHITIETHD.SoLuong AS VARCHAR(10)) + ')'
        FROM CHITIETHD
        JOIN SANPHAM ON CHITIETHD.MaSP = SANPHAM.MaSP
        WHERE CHITIETHD.MaHD = @MaHD
        FOR XML PATH('')
    ), 1, 2, '') AS ThongTinSanPham;
END
GO
--Xuất Thống kê: MaHD-TenKH-TenNV-NgayLHD-DSsanpham
CREATE PROC SP_READ_SELECT_XUATTK
AS
BEGIN
SELECT
    HOADON.MaHD,
    KHACHHANG.TenKH,
    NHANVIEN.TenNV,
    HOADON.NgayLapHD,
    STRING_AGG(CONCAT(SANPHAM.TenSP, '(', CHITIETHD.SoLuong, ')'), ', ') AS DanhSachSanPham
FROM
    HOADON
JOIN
    KHACHHANG ON HOADON.MaKH = KHACHHANG.MaKH
JOIN
    NHANVIEN ON HOADON.MaNV = NHANVIEN.MaNV
JOIN
    CHITIETHD ON HOADON.MaHD = CHITIETHD.MaHD
JOIN
    SANPHAM ON CHITIETHD.MaSP = SANPHAM.MaSP
GROUP BY
    HOADON.MaHD, KHACHHANG.TenKH, NHANVIEN.TenNV, HOADON.NgayLapHD
END
GO
--Đếm số lượng khách có mua hàng.
CREATE PROC SP_READ_SELECT_DEMKH_MUA
AS
BEGIN
SELECT COUNT(DISTINCT HOADON.MaKH) AS SoLuongKhachHang
FROM HOADON;
END
GO
--Đếm tổng số lượng mỗi sản phẩm được mua: SanPham1(10), SanPham2(30), ....
CREATE PROC SP_READ_SELECT_DEMSP_MUA
AS
BEGIN
SELECT
    STRING_AGG(CONCAT(TenSP, '(', SoLuong, ')'), ', ') AS DSSP
FROM
    (
        SELECT
            SANPHAM.TenSP,
            SUM(CHITIETHD.SoLuong) AS SoLuong
        FROM
            SANPHAM
        JOIN
            CHITIETHD ON SANPHAM.MaSP = CHITIETHD.MaSP
        GROUP BY
            SANPHAM.TenSP
    ) AS Subquery;

END
GO

CREATE PROC SP_TK_TongDoanhThu_Nam
AS
BEGIN
SELECT
    SUM(ch.SoLuong * sp.DonGia) AS TongDoanhThu
FROM
    CHITIETHD ch
JOIN
    SANPHAM sp ON ch.MaSP = sp.MaSP;
END



--**TIM KIEM THEO NGAY
CREATE PROC SP_TimKiemSP_Ngay @Ngay DATE
AS
BEGIN
SELECT
    HD.MaHD,
	KH.MaKH,
    KH.TenKH,
	NV.MaNV,
    NV.TenNV,
    CT.MaSP,
    SP.TenSP,
    CT.SoLuong,
	CT.SoLuong*SP.DonGia AS ThanhTien
FROM
    HOADON HD
    JOIN CHITIETHD CT ON HD.MaHD = CT.MaHD
    JOIN SANPHAM SP ON CT.MaSP = SP.MaSP
    JOIN KHACHHANG KH ON HD.MaKH = KH.MaKH
    JOIN NHANVIEN NV ON HD.MaNV = NV.MaNV
WHERE
    HD.NgayLapHD = @Ngay;
END
GO



/*USE PROC*/
--ADD
EXEC SP_ADD_KHACHHANG 'KH0','KHACH HANG LA', 'BACH HOA XANH', '18001085'
EXEC SP_ADD_KHACHHANG 'KH1','KHACH MOT', '1 THU DUC', '0111100001'
EXEC SP_ADD_KHACHHANG 'KH2','KHACH HAI', '2 THU DUC', '0111100002'
EXEC SP_ADD_KHACHHANG 'KH3','KHACH BA', '3 THU DUC', '0111100003'
EXEC SP_ADD_KHACHHANG 'KH4','KHACH BON', '4 THU DUC', '0111100004'
EXEC SP_ADD_KHACHHANG 'KH5','KHACH NAM', '5 THU DUC', '0111100005'

EXEC SP_ADD_NHANVIEN 'NV0', 'TRAINER', 'NAM', '01/01/2000', 'BACH HOA XANH', '18001085'
EXEC SP_ADD_NHANVIEN 'NV1', 'NGUYEN VAN MOT', 'NAM', '1/11/2001', '1 THU THIEM', '0222200001'
EXEC SP_ADD_NHANVIEN 'NV2', 'PHAN THI HAI', 'NU', '2/12/2002', '2 THU THIEM', '0222200002'
EXEC SP_ADD_NHANVIEN 'NV3', 'NGUYEN VAN BA', 'NAM', '3/11/2003', '3 THU THIEM', '0222200003'
EXEC SP_ADD_NHANVIEN 'NV4', 'PHAN THI BON', 'NU', '4/10/2004', '4 THU THIEM', '0222200004'
EXEC SP_ADD_NHANVIEN 'NV5', 'NGUYEN VAN NAM', 'NAM', '5/10/2005', '5 THU THIEM', '0222200005'

EXEC SP_ADD_HOADON 'HD1', 'KH1', 'NV1', '1/01/2023'
EXEC SP_ADD_HOADON 'HD2', 'KH2', 'NV2', '1/02/2023'
EXEC SP_ADD_HOADON 'HD3', 'KH3', 'NV3', '1/03/2023'
EXEC SP_ADD_HOADON 'HD4', 'KH4', 'NV4', '2/04/2023'
EXEC SP_ADD_HOADON 'HD5', 'KH5', 'NV5', '2/05/2023'
EXEC SP_ADD_HOADON 'HD6', 'KH1', 'NV1', '1/01/2023'

EXEC SP_ADD_SANPHAM	'SP0', 'SP Trong', 0, 'CAI', 0
EXEC SP_ADD_SANPHAM	'SP1', 'AO', 201, 'CAI', 1000
EXEC SP_ADD_SANPHAM	'SP2', 'BIA', 202, 'LON', 2500
EXEC SP_ADD_SANPHAM	'SP3', 'CHOI', 203, 'CAY', 3000
EXEC SP_ADD_SANPHAM	'SP4', 'DU DU', 204, 'TRAI', 4500
EXEC SP_ADD_SANPHAM	'SP5', 'EMP', 205,'LO', 5000

EXEC SP_ADD_CHITIETHD 'HD1', 'SP1', '11'
EXEC SP_ADD_CHITIETHD 'HD1', 'SP4', '14'
EXEC SP_ADD_CHITIETHD 'HD2', 'SP1', '21'
EXEC SP_ADD_CHITIETHD 'HD2', 'SP2', '22'
EXEC SP_ADD_CHITIETHD 'HD2', 'SP3', '23'
EXEC SP_ADD_CHITIETHD 'HD2', 'SP4', '24'
EXEC SP_ADD_CHITIETHD 'HD3', 'SP5', '35'
EXEC SP_ADD_CHITIETHD 'HD4', 'SP5', '45'
EXEC SP_ADD_CHITIETHD 'HD4', 'SP2', '42'
EXEC SP_ADD_CHITIETHD 'HD4', 'SP3', '43'
EXEC SP_ADD_CHITIETHD 'HD5', 'SP3', '53'
EXEC SP_ADD_CHITIETHD 'HD6', 'SP4', '64'

/* ĐƯỢC SỬ DỤNG TRONG FILE CODE CỦA C# */

--SELECT (NV.HoNV + ' ' + NV.TenNV) AS "HoTenNV"
--FROM NHANVIEN NV

--SELECT KH.TenKH
--FROM KHACHHANG KH

--SELECT (NV.HoNV + ' ' + NV.TenNV) AS "HoTenNV"
--FROM NHANVIEN NV, HOADON HD
--WHERE HD.MaHD = 'HD2' AND NV.MaNV = HD.MaNV

--SELECT KH.TenKH
--FROM KHACHHANG KH, HOADON HD
--WHERE HD.MaHD = 'HD2' AND KH.MaKH = HD.MaKH
